### ISSUE TITLE
Document file_engine in the docs guide on user input

### ISSUE THREAD

**Issue by MassiminoilTrace** [DioxusLabs/docsite#101]
At the https://dioxuslabs.com/learn/0.4/reference/user_input page, there's no mention on how to use input fields with `type="file"`.
Trying to print the oninput event using the debug formatting didn't help either, as only empty "value" and "values" fields did show up.
Then I found the existence of the `files` field from the docs generated by `cargo doc`, in the `dioxus::prelude::FormData`. After more searching, I found this other example showing file upload https://github.com/Demonthos/dioxus/blob/master/examples/file_upload.rs

I would suggest documenting the file input feature inside the "user_input" guide page at https://dioxuslabs.com/learn/0.4/reference/user_input page.

Can I help in some way? Be warned that I'm not a native english speaker, so a checking might be needed anyway.

**Comment by Demonthos** [comment]
That sounds like a great addition! Most of dioxus' events mirror the web api, so we don't have documentation on all events in the reference. It makes sense to at least document the file engine because it is significantly different from what you may use in javascript.

> Can I help in some way? Be warned that I'm not a native english speaker, so a checking might be needed anyway.

If you would like to add a section to the `user_input` documentation, I would be happy to check it!

**Comment by MassiminoilTrace** [comment]
Closed with #102
